### ISSUE TITLE
Make action a "composite" action

### ISSUE THREAD

**Issue by lihop** [lihop/godot-setup#12]
Using [actions/github-script](https://github.com/actions/github-script) would make it possible to run the `index.js` script via a composite action. Using a composite action will allow us to perform other actions (such as installing mesa-dist-win) using other dedicated actions rather than our home-made ones.
`index.js` will need to be updated to export the main function and take core, exec, and github as inputs.
```
runs:
  using: "composite"
  steps:
    - name: Setup Godot
      uses: "actions/github-script@v7"
      with:
        script: |
          const script = require("${{github.action_path}}/index.js")
          script({core, exec, github})
```
